table genres
	lineageTag: 84e8cee8-9bf9-4b54-814c-d54586dc592e

	column film
		dataType: string
		lineageTag: 9ca76d26-4fe5-453d-9a74-ae25f7317d0c
		summarizeBy: none
		sourceColumn: film

		annotation SummarizationSetBy = Automatic

	column category
		dataType: string
		lineageTag: 711fa8bd-d187-4405-a437-9a5a013e3cea
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = Automatic

	column value
		dataType: string
		lineageTag: bf3204d8-77a0-49e7-8a32-03cffcafffb5
		summarizeBy: none
		sourceColumn: value

		annotation SummarizationSetBy = Automatic

	partition genres = m
		mode: import
		source =
				let
				    Source = Csv.Document(Web.Contents("https://raw.githubusercontent.com/erictleung/pixarfilms/master/data-raw/genres.csv"),[Delimiter=",", Columns=3, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"film", type text}, {"category", type text}, {"value", type text}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

